security:
    always_authenticate_before_granting: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_VERIFIED]

    encoders:
        App\Entity\User: bcrypt

    providers:
        database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: app_user_index
                check_path: app_user_login
            logout:
                path: /logout
                target: /

    access_control:
