home:
    resource: ../../src/Controller/HomeController.php
    type: annotation
    prefix: /

guest_admin:
    resource: ../../src/Controller/GuestAdminController.php
    type: annotation
    prefix: /{_locale}/admin/guest
    requirements:
        _locale: nl|es
rsvp:
    resource: ../../src/Controller/RsvpController.php
    type: annotation
    prefix: /{_locale}/rsvp
    requirements:
        _locale: nl|es

user:
    resource: ../../src/Controller/UserController.php
    type: annotation
    prefix: /{_locale}/user
    requirements:
        _locale: nl|es

user_admin:
    resource: ../../src/Controller/UserAdminController.php
    type: annotation
    prefix: /{_locale}/admin/user
    requirements:
        _locale: nl|es
