home:
    resource: ../../src/Controller/HomeController.php
    type: annotation
    prefix: /

user:
    resource: ../../src/Controller/UserController.php
    type: annotation
    prefix: /{_locale}/user
    requirements:
        _locale: nl|es

user_admin:
    resource: ../../src/Controller/UserAdminController.php
    type: annotation
    prefix: /{_locale}/admin/user
    requirements:
        _locale: nl|es
