home:
    resource: ../../src/Controller/HomeController.php
    type: annotation
    prefix: /

guest_admin:
    resource: ../../src/Controller/GuestAdminController.php
    type: annotation
    prefix: /admin/guest

rsvp:
    resource: ../../src/Controller/RsvpController.php
    type: annotation
    prefix: /rsvp

user:
    resource: ../../src/Controller/UserController.php
    type: annotation
    prefix: /user

user_admin:
    resource: ../../src/Controller/UserAdminController.php
    type: annotation
    prefix: /admin/user

page:
    resource: ../../src/Controller/PageController.php
    type: annotation
    prefix: /
